update

diff --git a/bin/fzf_bundle_exec_rake b/bin/fzf_bundle_exec_rake
--- a/bin/fzf_bundle_exec_rake
+++ b/bin/fzf_bundle_exec_rake
@@ -2,13 +2,37 @@
 
 # bundle exec rakeで実行するタスクの候補を表示する。
 # プレビューとして、タスクのソースコードを表示する。
+RG_CMD="rg --line-number --color=never --hidden -g '*.rake' --sort=path '(namespace .*do|task_with_logger)'"
+RG_RESULT=$(eval "${RG_CMD}")
+if [[ -z ${RG_RESULT} ]]; then
+  echo "Not found."
+  exit $?
+fi
 
-files=$(rg --files --color=never --hidden -g '*.rake' --sort=path) || return
 target=$(
-  rg --line-number --color=never --hidden -g '*.rake' --sort=path "(namespace .*do|task_with_logger)" \
+  echo "${RG_RESULT}" \
+    | grep -Ev " *# *namespace .*do" \
+    | grep -Ev " *# *task_with_logger .*" \
     | awk -F ':' '{ for (i=1;i<=NF;i++) { sub(",", " ", $i); gsub("'"'"'", " ", $i); printf "%s ", $i}; printf "\n" }' \
     | awk '{ for (i=1;i<=NF;i++) { printf "%s ", $i}; printf "\n" }' \
-    | awk 'BEGIN { NS=""; TASK="" } { if ($3 == "namespace") { NS=$4;} else { TASK=$4; FILE=$1; LINE=$2; printf "\033[38;5;33m%s:%s\033[0m\t%s %s\n", NS, TASK, FILE, LINE } }' \
+    | awk '
+      BEGIN {
+        NAMESPACE = "@NAMESPACE_NOT_SET@";
+        FILE = "";
+        TASK = ""
+      } {
+        if (FILE != $1) {
+          NAMESPACE = "@NAMESPACE_NOT_SET@";
+          FILE = $1;
+        }
+        if ($3 == "namespace") {
+          NAMESPACE=$4
+        } else {
+          LINE = $2;
+          TASK = $4;
+          printf "\033[38;5;33m%s:%s\033[0m\t%s %s\n", NAMESPACE, TASK, FILE, LINE
+        }
+      }' \
     | fzf --info=inline \
       --nth=1 \
       --ansi \
@@ -17,7 +41,7 @@ target=$(
       --bind "ctrl-v:execute(nvim {2} +{3} < /dev/tty > /dev/tty)" \
       --bind 'ctrl-/:toggle-preview' \
       --preview 'bat --color=always --line-range {3}: --highlight-line {3} {2}' \
-      --preview-window=right:60%:wrap)
+      --preview-window=down:70%:wrap)
 ret_cd=$?
 if [ ${ret_cd} -eq 0 ]; then
   echo "${target}"|awk '{ print $1 }'
diff --git a/bin/git_grep b/bin/git_grep
--- a/bin/git_grep
+++ b/bin/git_grep
@@ -33,9 +33,16 @@ done
 # そのためNULL文字はperlで置換する（タブ文字にする）。
 # ファイルとファイルの区切りは '--' となるが、これは検索結果的には邪魔である。
 # そのため grep -v で'--' の行を除去する。
-GIT_GREP_CMD="git grep --show-function --null --line-number --color=never --extended-regexp ${PARAMS}| perl -pe 's/\x0/\t/g'| grep -v '\-\-'"
+GIT_GREP_CMD="git grep --null --line-number --color=never --extended-regexp ${PARAMS}| perl -pe 's/\x0/\t/g'| grep -v '\-\-'"
 FZF_PROMPT="$(basename $0) ${PARAMS}"
 FZF_HEADER="enter:nvim"
 GIT_GREP_RESULT=$(eval "${GIT_GREP_CMD}")
-echo "${GIT_GREP_RESULT}"| awk -v GREP_RESULT_COUNT="$(echo "${GIT_GREP_RESULT}"| wc -l| tr -d ' ')" '{ printf "(%3d/%d)	%s\n", NR, GREP_RESULT_COUNT, $0 }'
+GIT_GREP_EXIT_CD=$?
+if [[ "${GIT_GREP_EXIT_CD}" != 0 ]]; then
+  echo "Not found"
+  exit ${GIT_GREP_EXIT_CD}
+else
+  echo "${GIT_GREP_RESULT}"| awk -v GREP_RESULT_COUNT="$(echo "${GIT_GREP_RESULT}"| wc -l| tr -d ' ')" '{ printf "(%3d/%d)	%s\n", NR, GREP_RESULT_COUNT, $0 }'
+  exit 0
+fi
 
diff --git a/bin/git_grep_fzf_vim b/bin/git_grep_fzf_vim
--- a/bin/git_grep_fzf_vim
+++ b/bin/git_grep_fzf_vim
@@ -33,32 +33,38 @@ done
 # そのためNULL文字はperlで置換する（タブ文字にする）。
 # ファイルとファイルの区切りは '--' となるが、これは検索結果的には邪魔である。
 # そのため grep -v で'--' の行を除去する。
-GIT_GREP_CMD="git grep --show-function --null --line-number --color=always --extended-regexp "${PARAMS}"| perl -pe 's/\x0/\t/g'| grep -v '\-\-'"
+GIT_GREP_CMD="git grep --null --line-number --color=always --extended-regexp "${PARAMS}"| perl -pe 's/\x0/\t/g'| grep -v '\-\-'"
 FZF_PROMPT="$(basename $0) ${PARAMS}"
 FZF_HEADER="enter:nvim"
 GIT_GREP_RESULT=$(eval "${GIT_GREP_CMD}")
-FZF_REZULT=$(echo "${GIT_GREP_RESULT}" \
-  | awk -v GREP_RESULT_COUNT="$(echo "${GIT_GREP_RESULT}"| wc -l| tr -d ' ')" '{ printf "(%3d/%d)	%s\n", NR, GREP_RESULT_COUNT, $0 }' \
-  | fzf -m \
-    --ansi \
-    --info=inline \
-    --delimiter='	' \
-    --tabstop=2 \
-    --prompt="${FZF_PROMPT} > " \
-    --header="${GIT_GREP_CMD}" \
-    --bind "ctrl-c:print-query" \
-    --bind "ctrl-f:page-down" \
-    --bind "ctrl-b:page-up" \
-    --bind "ctrl-/:toggle-preview" \
-    --bind "tab:execute(git_pr_show_by_file_line {2} {3})" \
-    --bind "ctrl-o:execute(git_pr_open_by_file_line {2} {3})" \
-    --bind "ctrl-p:execute(git_pr_open_by_file_line {2} {3})" \
-    --bind="enter:execute(nvim {2} +{3} < /dev/tty > /dev/tty)" \
-    --preview-window"=wrap:bottom:65%"\
-    --preview="git blame -L {3},{3} {2}| awk '{ print \$1 }'; git_blame_colored {2} {3} ${SEARCH_WORD} {q}"
-  )
+GIT_GREP_EXIT_CD=$?
+if [[ "${GIT_GREP_EXIT_CD}" != 0 ]]; then
+  echo "Not found"
+  exit ${GIT_GREP_EXIT_CD}
+else
+  FZF_REZULT=$(echo "${GIT_GREP_RESULT}" \
+    | awk -v GREP_RESULT_COUNT="$(echo "${GIT_GREP_RESULT}"| wc -l| tr -d ' ')" '{ printf "(%3d/%d)	%s\n", NR, GREP_RESULT_COUNT, $0 }' \
+    | fzf -m \
+      --ansi \
+      --info=inline \
+      --delimiter='	' \
+      --tabstop=2 \
+      --prompt="${FZF_PROMPT} > " \
+      --header="${GIT_GREP_CMD}" \
+      --bind "ctrl-c:print-query" \
+      --bind "ctrl-f:page-down" \
+      --bind "ctrl-b:page-up" \
+      --bind "ctrl-/:toggle-preview" \
+      --bind "tab:execute(git_pr_show_by_file_line {2} {3})" \
+      --bind "ctrl-o:execute(git_pr_open_by_file_line {2} {3})" \
+      --bind "ctrl-p:execute(git_pr_open_by_file_line {2} {3})" \
+      --bind="enter:execute(nvim {2} +{3} < /dev/tty > /dev/tty)" \
+      --preview-window"=wrap:bottom:65%"\
+      --preview="git_blame_colored {2} {3} \"${SEARCH_WORD}\" {q}"
+    )
 
-if [[ ! -z "${FZF_REZULT}" ]]; then
-  echo "QUERY> ${FZF_REZULT}"
+  if [[ ! -z "${FZF_REZULT}" ]]; then
+    echo "QUERY> ${FZF_REZULT}"
+  fi
 fi
 
