update

diff --git a/bin/git_deepblame b/bin/git_deepblame
--- a/bin/git_deepblame
+++ b/bin/git_deepblame
@@ -1,17 +1,7 @@
 #!/bin/bash
 perl_epocms() { perl -MTime::HiRes -e 'printf("%.0f\n",Time::HiRes::time()*1000)'; }
-
-hline() {
-  if ( tput cols>/dev/null 2>&1 ); then
-    # fzfの動作上、ちょっと減らしたほうが見た目が良い気がしたので-10。
-    col_size=$(( $(tput cols) - 10 ))
-  else
-    # 数字の根拠は特になし。適当です。
-    col_size=16
-  fi
-  eval printf '%.0s-' "{1..${col_size}}"
-  echo
-}
+hline() { eval printf '%.0s-' "{1..120}"; echo; return 0; }
+readonly DELIMITER=$'\t'
 
 start_time_millis=$(perl_epocms)
 # 特定の文言を含むコミットを抽出します。
@@ -24,9 +14,9 @@ files=""
 while (( $# > 0 )); do
   case $1 in
     --range) range=" $2"; shift ;;
-    --) shift; files=$@; break ;;
+    --) shift; files="$*"; break ;;
     *)
-      if [[ ! -z "${q_raw}" ]]; then
+      if [[ -n "${q_raw}" ]]; then
         echo "Usage: $(basename $0) 'searchword' --range commit1...commit2 -- files"
         exit 1
       else
@@ -41,115 +31,67 @@ if [[ -z "${q_raw}" ]]; then
   exit 0
 fi
 
-BS="\\"
-logic=0
-if [[ ${logic} == 0 ]]; then
-  q_shell_escaped=${q_raw}
-  q_shell_escaped=${q_shell_escaped//\\/${BS}\\}
-  q_shell_escaped=${q_shell_escaped//\`/${BS}\`}
-  q_shell_escaped=${q_shell_escaped//\~/${BS}\~}
-  q_shell_escaped=${q_shell_escaped//\!/${BS}\!}
-  q_shell_escaped=${q_shell_escaped//\@/${BS}\@}
-  q_shell_escaped=${q_shell_escaped//\#/${BS}\#}
-  q_shell_escaped=${q_shell_escaped//\$/${BS}\$}
-  q_shell_escaped=${q_shell_escaped//\%/${BS}\%}
-  q_shell_escaped=${q_shell_escaped//\^/${BS}\^}
-  q_shell_escaped=${q_shell_escaped//\&/${BS}\&}
-  q_shell_escaped=${q_shell_escaped//\*/${BS}\*}
-  q_shell_escaped=${q_shell_escaped//\(/${BS}\(}
-  q_shell_escaped=${q_shell_escaped//\)/${BS}\)}
-  q_shell_escaped=${q_shell_escaped//\-/${BS}-}
-  q_shell_escaped=${q_shell_escaped//\+/${BS}+}
-  q_shell_escaped=${q_shell_escaped//\_/${BS}_}
-  q_shell_escaped=${q_shell_escaped//\=/${BS}=}
-  q_shell_escaped=${q_shell_escaped//\{/${BS}\{}
-  q_shell_escaped=${q_shell_escaped//\}/${BS}\}}
-  q_shell_escaped=${q_shell_escaped//\[/${BS}[}
-  q_shell_escaped=${q_shell_escaped//\]/${BS}]}
-  q_shell_escaped=${q_shell_escaped//\|/${BS}|}
-  q_shell_escaped=${q_shell_escaped//\?/${BS}?}
-  q_shell_escaped=${q_shell_escaped//\./${BS}.}
-  q_shell_escaped=${q_shell_escaped//\,/${BS},}
-  q_shell_escaped=${q_shell_escaped//\//${BS}/}
-  q_shell_escaped=${q_shell_escaped//\</[${BS}\<]}
-  q_shell_escaped=${q_shell_escaped//\>/[${BS}\>]}
-else
-  q_shell_escaped=$(printf '%s\n' "${q_raw}"| sed -e 's/[^^]/[&]/g; s/\^/\\^/g')
-  q_shell_escaped="${q_shell_escaped//\`/\\\`}"
-  q_shell_escaped="${q_shell_escaped//\"/\\\"}"
-  q_shell_escaped="${q_shell_escaped}"
-fi
+q_shell_escaped=$(printf '%s\n' "${q_raw}"| sed -e 's/[^^]/[&]/g; s/\^/\\^/g')
+q_shell_escaped="${q_shell_escaped//\`/\\\`}"
+q_shell_escaped="${q_shell_escaped//\"/\\\"}"
 
-fzf_prompt="[$(basename $0)] in=${range}, files=${files}, q_raw=${q_raw}, q_shell_escaped=${q_shell_escaped}"
-printf "%s\n" "${fzf_prompt}"
+cd $(git_obtain_root "$files") && (
+  printf "[%s]\n" "$(basename $0)"
+  printf "PARAMETERS\n  in=%s\n  files=%s\n  q_raw=%s\n  q_shell_escaped=%s\n" "${range}" "${files}" "${q_raw}" "${q_shell_escaped}"
+  git_log_g_res_cmd="git --no-pager log --date=format:'%Y-%m-%d %H:%M' --pretty='%h	%ad	%an	%s' -G\"${q_shell_escaped}\"${range} -- ${files}"
+  printf "BASE GIT LOG COMMAND\n  %s\n" "${git_log_g_res_cmd}"
+  git_log_g_res=$(eval "${git_log_g_res_cmd}")
+  if [[ -z "${git_log_g_res}" ]]; then
+    echo "not found."
+    exit 1
+  fi
+  git_log_g_res_size=$(printf "%s" "${git_log_g_res}"| grep -Evc '^$')
 
-git_log_g_res_cmd="git --no-pager log --date=format:'%Y-%m-%d %H:%M' --pretty='%h	%ad	%an	%s' -G\"${q_shell_escaped}\"${range} -- ${files}"
-printf "%s\n" "${git_log_g_res_cmd}"
-git_log_g_res=$(eval "${git_log_g_res_cmd}")
-if [[ -z "${git_log_g_res}" ]]; then
-  echo "not found."
-  exit 1
-fi
-git_log_g_res_size=$(printf "%s" "${git_log_g_res}"| grep -Evc '^$')
-
-(
-  git_log_g_res_idx=0
-  IFS=$'\n'
-  for git_log_g_res_1 in $(echo "${git_log_g_res}"); do
-    git_log_g_res_idx=$(( git_log_g_res_idx + 1 ))
-    single_commit_start_time_millis=$(perl_epocms)
-    # １コミットの各要素を取得します(%h, %ad, %an, %s)。
-    git_log_h=$(echo "${git_log_g_res_1}"| awk -F '\t' '{ print $1 }')
-    git_log_ad=$(echo "${git_log_g_res_1}"| awk -F '\t' '{ printf "%s", $2 }')
-    git_log_an=$(echo "${git_log_g_res_1}"| awk -F '\t' '{ printf "%s", $3 }')
-    git_log_s=$(echo "${git_log_g_res_1}"| awk -F '\t' '{ printf "%s", $4 }')
-    if ( echo "${git_log_s}"| grep -Eo "[(]#[0-9]+[)]">/dev/null 2>&1 ); then
-      pull_request_no=$(echo "${git_log_s}"| grep -Eo "[(]#[0-9]+[)]"| tail -1)
-    else
-      pull_request_no="(#.....)"
-    fi
-
-    string_buffer=""
-    git_log_patch_filename=""
-    line_to_process=$(git --no-pager log --oneline -1 --patch --unified=0 ${git_log_h} -- ${files}| tail +2| grep -E "(^diff --git|^[\+|\-].*${q_shell_escaped})"| grep -Ev '^([\+]{3} b/|[\-]{3} a/)')
-    for git_log_patch_res_1 in $(printf "%s" "${line_to_process}"); do
-      if ( echo "${git_log_patch_res_1}"| grep -E "^diff --git a/.* b/.*">/dev/null 2>&1 ); then
-        git_log_patch_filename_a=$(echo "${git_log_patch_res_1}"| sed -E 's/^(diff --git )a\/(.*) b\/(.*)$/\2/')
-        git_log_patch_filename_b=$(echo "${git_log_patch_res_1}"| sed -E 's/^(diff --git )a\/(.*) b\/(.*)$/\3/')
-        git_log_patch_filename=$(echo "${git_log_patch_filename_a}"$'\n'"${git_log_patch_filename_b}"| uniq| xargs echo)
+  (
+    git_log_g_res_idx=0
+    IFS=$'\n'
+    for git_log_g_res_1 in $(echo "${git_log_g_res}"); do
+      git_log_g_res_idx=$(( git_log_g_res_idx + 1 ))
+      # single_commit_start_time_millis=$(perl_epocms)
+      # １コミットの各要素を取得します(%h, %ad, %an, %s)。
+      git_log_h=$(echo "${git_log_g_res_1}"| awk -F '\t' '{ print $1 }')
+      git_log_ad=$(echo "${git_log_g_res_1}"| awk -F '\t' '{ printf "%s", $2 }')
+      git_log_an=$(echo "${git_log_g_res_1}"| awk -F '\t' '{ printf "%s", $3 }')
+      git_log_s=$(echo "${git_log_g_res_1}"| awk -F '\t' '{ printf "%s", $4 }')
+      if ( echo "${git_log_s}"| grep -Eo "[(]#[0-9]+[)]">/dev/null 2>&1 ); then
+        pull_request_no=$(echo "${git_log_s}"| grep -Eo "[(]#[0-9]+[)]"| tail -1)
       else
-        if ( printf '%s\n' "${git_log_patch_res_1}"| grep -E "${q_shell_escaped}">/dev/null 2>&1 ); then
-          git_log_patch_res_1_head1="${git_log_patch_res_1:0:1}"
-          if [[ "${git_log_patch_res_1_head1}" == "+" ]]; then
-            readable_label="追加"
-          elif [[ "${git_log_patch_res_1_head1}" == "-" ]]; then
-            readable_label="削除"
-          fi
-          string_buffer+="${git_log_h}	${pull_request_no}	${git_log_ad}	${git_log_an}	${git_log_patch_filename}	|${readable_label}|${git_log_patch_res_1}"$'\n'
-        fi
+        pull_request_no="(#.....)"
       fi
+
+      string_buffer=""
+      git_log_patch_filename=""
+      line_to_process=$(git --no-pager log --oneline -1 --patch --unified=0 ${git_log_h} -- ${files}| tail +2| grep -E "(^diff --git|^[\+|\-].*${q_shell_escaped})"| grep -Ev '^([\+]{3} b/|[\-]{3} a/)')
+      for git_log_patch_res_1 in $(printf "%s" "${line_to_process}"); do
+        if ( echo "${git_log_patch_res_1}"| grep -E "^diff --git a/.* b/.*">/dev/null 2>&1 ); then
+          git_log_patch_filename_a=$(echo "${git_log_patch_res_1}"| sed -E 's/^(diff --git )a\/(.*) b\/(.*)$/\2/')
+          git_log_patch_filename_b=$(echo "${git_log_patch_res_1}"| sed -E 's/^(diff --git )a\/(.*) b\/(.*)$/\3/')
+          git_log_patch_filename=$(echo "${git_log_patch_filename_a}"$'\n'"${git_log_patch_filename_b}"| uniq| xargs echo)
+        else
+          if ( printf '%s\n' "${git_log_patch_res_1}"| grep -E "${q_shell_escaped}">/dev/null 2>&1 ); then
+            git_log_patch_res_1_head1="${git_log_patch_res_1:0:1}"
+            if [[ "${git_log_patch_res_1_head1}" == "+" ]]; then
+              readable_label="追加"
+            elif [[ "${git_log_patch_res_1_head1}" == "-" ]]; then
+              readable_label="削除"
+            fi
+            #string_buffer+="(${git_log_g_res_idx}/${git_log_g_res_size}) ${git_log_h}	${pull_request_no}	${git_log_ad}	${git_log_an}	${git_log_patch_filename}"$'\n'
+            string_buffer+="(${git_log_g_res_idx}/${git_log_g_res_size})${DELIMITER}${git_log_h}${DELIMITER}${pull_request_no}${DELIMITER}${git_log_patch_filename}${DELIMITER}|${readable_label}|${git_log_patch_res_1}"$'\n'
+          fi
+        fi
+      done
+
+      hline
+      printf "%s\n" "(${git_log_g_res_idx}/${git_log_g_res_size})${DELIMITER}${git_log_h}${DELIMITER}${pull_request_no}${DELIMITER}${git_log_ad}${DELIMITER}${git_log_an}${DELIMITER}${git_log_s}"
+      printf "%s\n" "${string_buffer}"| grep -Ev "^$"
     done
-
-    printf "%s\n" "${git_log_h}	${pull_request_no}	${git_log_ad}	${git_log_an}	${git_log_s}"
-    printf "%s\n" "${string_buffer}"| grep -Ev "^$"
-    time_millis=$(perl_epocms)
-    single_commit_elapsed_time_millis=$(( time_millis - single_commit_start_time_millis ))
-    elapsed_time_millis=$(( time_millis - start_time_millis ))
-    # printf "... %dms (%s/%s) elapsed:%dms \n" "${single_commit_elapsed_time_millis}" "${git_log_g_res_idx}" "${git_log_g_res_size}" "${elapsed_time_millis}"
-    printf "(%s/%s)\n" "${git_log_g_res_idx}" "${git_log_g_res_size}"
+    elapsed_time_millis=$(( $(perl_epocms) - start_time_millis ))
     hline
-  done
-  elapsed_time_millis=$(( $(perl_epocms) - start_time_millis ))
-  echo "検索完了です(${git_log_g_res_size}commits, ${elapsed_time_millis}ms)"
-)| grep -E --color=always "$|${q_shell_escaped}"
-# 最終行のところ、fzfやtigを使ってるならさらに以下を追記しても良いです。
-# )| grep -E --color=always "$|${q_shell_escaped}"
-#      --delimiter="\t"\
-#      --tabstop=2\
-#      --ansi\
-#      --info=inline\
-#      --prompt="${fzf_prompt} "\
-#      --header="${git_log_g_res_size}commits hits..."\
-#      --bind="enter:execute(tig {1} -1 -G\"${q_shell_escaped}\" -- {5})"\
-#      --bind="#:execute(printf {1}| pbcopy; printf 'ハッシュ値({1})をコピーしましたよ。'; read )"
-
+    echo "検索完了です(${git_log_g_res_size}commits, ${elapsed_time_millis}ms)"
+  )| grep -E --color=always "$|${q_shell_escaped}"
+)
